version: "3.1"
name: castor-dev
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CASTOR_SERVER_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CASTOR_SERVER_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-dev:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${CASTOR_SERVER_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${CASTOR_SERVER_DB_USERNAME}:${CASTOR_SERVER_DB_PASSWORD}@mongo:${CASTOR_SERVER_DB_PORT}/

  agent:
    image: castor-dev/agent:latest
    build:
      context: ./
      dockerfile: ./agent/Dockerfile
    restart: always
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
    deploy:
      replicas: 1 # Change this to the number of agents you want

  worker:
    image: castor/worker:latest
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URI: mongodb://CASTOR_SERVER_DB_USERNAME:${CASTOR_SERVER_DB_PASSWORD}@mongo:${CASTOR_SERVER_DB_PORT}/
      CASTOR_SERVER_DB_HOST: mongo
      CASTOR_SERVER_DB_PORT: ${CASTOR_SERVER_DB_PORT}
      CASTOR_SERVER_DB_USERNAME: ${CASTOR_SERVER_DB_USERNAME}
      CASTOR_SERVER_DB_PASSWORD: ${CASTOR_SERVER_DB_PASSWORD}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  frontend:
    image: castor-dev/frontend:latest
    build: ./frontend
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CASTOR_SERVER_HOST=api
      - CASTOR_SERVER_PORT=8000

  api:
    build:
      context: ./castor_server
      dockerfile: ./deploy/Dockerfile
      target: dev
    image: castor_server:${CASTOR_SERVER_VERSION:-latest}
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./castor_server:/app/src/
    env_file:
    - .env
    environment:
      CASTOR_SERVER_HOST: 0.0.0.0
      CASTOR_SERVER_DB_HOST: mongo

volumes:
  mongo-dev:
