version: "3.1"
name: castor
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $CASTOR_SERVER_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CASTOR_SERVER_DB_PASSWORD}
    ports:
      - ${CASTOR_SERVER_DB_PORT}:${CASTOR_SERVER_DB_PORT}
    volumes:
      - mongo:/data/db

  agent:
    image: castor/agent:latest
    build: ./agent
    restart: always
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
    deploy:
      replicas: 1 # Change this to the number of agents you want

  worker:
    image: castor/worker:latest
    build: ./worker
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URI: mongodb://${CASTOR_SERVER_DB_HOST}:${CASTOR_SERVER_DB_PASSWORD}@mongo:${CASTOR_SERVER_DB_PORT}/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  api:
    build:
      context: ./castor_server
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: castor_server:${CASTOR_SERVER_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      CASTOR_SERVER_HOST: 0.0.0.0
      CASTOR_SERVER_DB_HOST: mongo

volumes:
  mongo:
