version: "3.1"
name: castor-agent
services:
  agent:
    image: castor/agent:latest
    build: .
    restart: always
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
    deploy:
      replicas: 1 # Change this to the number of agents you want
